# Example Dockerfile
# docker build -t slack_boltjs_app -f Dockerfile.example . && docker run -p 3000:3000 --env-file .env -d slack_boltjs_app
FROM node:16.20.0-slim

WORKDIR /usr/app
COPY --chown=node:node ./ ./
RUN npm install
USER node
EXPOSE 3000

CMD ["npm", "start"]
